### PR TITLE
Fix handling of --tag option: it must be set on npm.load()

### PR DESCRIPTION
**Pull request by seanpk**
- `{ tag: 'whatever' }` must be passed to the `npm.load()` function for it to fully take effect
- required a new kind of tests for that option (**test/outside-in.js**)
- added new "--test" option to support running publish without actually doing the publish
- also updated mocha dependency and fixed some other failing tests

as promised in issue #4

### CODE REVIEW

**Comment by seanpk** [comment]
re: the travis failure

the new tests (in test/outside-in.js) use `child_process`, which has a different API now than it did in node v0.11
they do work locally for me on v4.4.1, as do the real actions with `--tag`

**Comment by cmanzana** [comment]
could you change the travis yaml to refer to newer versions of node? then I believe travis CI build will be ok and I can merge the pull request

**Comment by seanpk** [comment]
Turns out it wasn't the changes to `child_process` that was at fault, but that `String.prototype.includes` didn't exist before v4.

**Comment by seanpk** [comment]
Thanks for pulling this in @cmanzana.
When do you plan to publish 0.6.0 to npm?

**Comment by cmanzana** [comment]
done! and thanks to you for contributing!

**Comment by seanpk** [comment]
awesome, thanks!

**Pull request merged**
